apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    add-deployment-name-label: "True"
  name: test-app
  namespace: test-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx